version: "3.8"

services:
  react:
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - public
    volumes:
      - ./:/app
      - ./node_modules:/app/node_modules
    container_name: react_frontend

networks:
  public:
    driver: bridge
